# Generated by Django 4.2.4 on 2023-11-19 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stuprofile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='materias',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='competencias',
        ),
        migrations.AddField(
            model_name='bloom',
            name='materia',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='stuprofile.materia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materia',
            name='docentes',
            field=models.ManyToManyField(related_name='materias', to='stuprofile.docente'),
        ),
    ]
